
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analise;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int CADEIA_CARACTERES = 11;
  public static final int MENOR = 23;
  public static final int SOMA_OP = 17;
  public static final int IGUAL = 24;
  public static final int INTEIRO_NUM = 9;
  public static final int END = 12;
  public static final int Close_C = 16;
  public static final int POTENCIACAO_OP = 21;
  public static final int DIVISAO_OP = 20;
  public static final int MULTIPLICACAO_OP = 19;
  public static final int Texto = 5;
  public static final int Negado = 26;
  public static final int ID = 2;
  public static final int Open_Key = 13;
  public static final int Close_Par = 7;
  public static final int Open_C = 15;
  public static final int EOF = 0;
  public static final int NUMBER = 8;
  public static final int Repeticao = 27;
  public static final int Aceito = 25;
  public static final int Flutuante = 4;
  public static final int SUBTRACAO_OP = 18;
  public static final int FLUTUANTE_NUM = 10;
  public static final int MAIOR = 22;
  public static final int error = 1;
  public static final int ATT = 28;
  public static final int Close_Key = 14;
  public static final int Inteiro = 3;
  public static final int Open_Par = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "Inteiro",
  "Flutuante",
  "Texto",
  "Open_Par",
  "Close_Par",
  "NUMBER",
  "INTEIRO_NUM",
  "FLUTUANTE_NUM",
  "CADEIA_CARACTERES",
  "END",
  "Open_Key",
  "Close_Key",
  "Open_C",
  "Close_C",
  "SOMA_OP",
  "SUBTRACAO_OP",
  "MULTIPLICACAO_OP",
  "DIVISAO_OP",
  "POTENCIACAO_OP",
  "MAIOR",
  "MENOR",
  "IGUAL",
  "Aceito",
  "Negado",
  "Repeticao",
  "ATT"
  };
}

